spring:
  application:
    name: wallet-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:postgresql}:${DB_PORT:5432}/${DB_NAME:wallet_db}
    username: ${DB_LOGIN:user}
    password: ${DB_PASSWORD:password}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    default-schema: public
    parameters:
      searchPath: classpath:/db/changelog/

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20

server:
  port: ${APPLICATION_PORT:8089}
  servlet:
    context-path: ${CONTEXT_APPLICATION:/api/v1}