spring:
  application:
    name: wallet-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:postgresql}:${DB_PORT:5432}/${DB_NAME:wallet_db}
    username: ${DB_LOGIN:user}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 30000
      leak-detection-threshold: 5000

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    default-schema: public
    parameters:
      searchPath: classpath:/db/changelog/

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60s

server:
  tomcat:
    threads:
      max: 500
    accept-count: 100
  port: ${APPLICATION_PORT:8089}
  servlet:
    context-path: ${CONTEXT_APPLICATION:/api/v1}